name: html_up
description: A starting point for Dart libraries or applications.
version: 1.0.5
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  html: ^0.15.5
  # path: ^1.8.0

dev_dependencies:
  very_good_analysis: ^6.0.0
